# Generated by Django 4.1.2 on 2023-03-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_index', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_cleared', models.BooleanField(blank=True, default=False)),
                ('total_played', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('played_count', models.IntegerField(blank=True, default=0)),
                ('playlist_id', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, to='api.playlist')),
                ('video_id', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='api.youtubevideo')),
            ],
        ),
    ]
