# Generated by Django 4.1.2 on 2023-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_queue_channel_title_queue_description_queue_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='channel_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
