# Generated by Django 4.1.2 on 2023-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_played_queue_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='played_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
