# Generated by Django 4.1.2 on 2023-03-12 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='current_queue_id',
            field=models.ForeignKey(blank=True, db_column='current_queue_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.queue'),
        ),
    ]
